# @package _global_

correctness_evaluator:
  _target_: recipe.evaluation.LLMJudgeCorrectnessEvaluator
  judge_model:
    _target_: recipe.models.TogetherAIAPI
    together_model_name: meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
    temperature: 0.
    max_tokens: 100
    seed: ${seed}
  save_dir: ${save_dir}
